/* えいご のことば（この言葉知ってる？クロスワードパズル）
   [表記, よみ, カギ]。表記・よみ は 大文字の英単語（A〜Z、2〜10字）。カギは 日本語の意味。
   小学校の外国語で 習う 単語から。 */
SUBJECTS.push({id:'eigo', name:'えいご', e:'🔤', alpha:true, groups:[
  {id:'food', name:'たべもの・どうぶつ', e:'🍎', words:[
    ['APPLE','APPLE','りんご 🍎'],
    ['BANANA','BANANA','バナナ 🍌'],
    ['ORANGE','ORANGE','オレンジ（くだもの）🍊'],
    ['GRAPES','GRAPES','ぶどう 🍇'],
    ['PEACH','PEACH','もも 🍑'],
    ['MELON','MELON','メロン 🍈'],
    ['LEMON','LEMON','レモン 🍋'],
    ['CHERRY','CHERRY','さくらんぼ 🍒'],
    ['STRAWBERRY','STRAWBERRY','いちご 🍓'],
    ['TOMATO','TOMATO','トマト 🍅'],
    ['POTATO','POTATO','じゃがいも 🥔'],
    ['CARROT','CARROT','にんじん 🥕'],
    ['BREAD','BREAD','パン 🍞'],
    ['RICE','RICE','ごはん・お米 🍚'],
    ['EGG','EGG','たまご 🥚'],
    ['MILK','MILK','牛にゅう 🥛'],
    ['JUICE','JUICE','ジュース 🧃'],
    ['CAKE','CAKE','ケーキ 🍰'],
    ['PIZZA','PIZZA','ピザ 🍕'],
    ['SALAD','SALAD','サラダ 🥗'],
    ['HAMBURGER','HAMBURGER','ハンバーガー 🍔'],
    ['SANDWICH','SANDWICH','サンドイッチ 🥪'],
    ['SUSHI','SUSHI','すし 🍣'],
    ['FISH','FISH','さかな 🐟'],
    ['DOG','DOG','犬 🐶'],
    ['CAT','CAT','ねこ 🐱'],
    ['RABBIT','RABBIT','うさぎ 🐰'],
    ['BEAR','BEAR','くま 🐻'],
    ['LION','LION','ライオン 🦁'],
    ['TIGER','TIGER','トラ 🐯'],
    ['ELEPHANT','ELEPHANT','ぞう 🐘'],
    ['MONKEY','MONKEY','さる 🐵'],
    ['PANDA','PANDA','パンダ 🐼'],
    ['KOALA','KOALA','コアラ 🐨'],
    ['HORSE','HORSE','うま 🐴'],
    ['COW','COW','牛 🐮'],
    ['PIG','PIG','ぶた 🐷'],
    ['MOUSE','MOUSE','ねずみ 🐭'],
    ['SNAKE','SNAKE','へび 🐍'],
    ['FROG','FROG','かえる 🐸'],
    ['BIRD','BIRD','鳥 🐦'],
    ['PENGUIN','PENGUIN','ペンギン 🐧'],
    ['GIRAFFE','GIRAFFE','キリン 🦒'],
    ['DOLPHIN','DOLPHIN','イルカ 🐬'],
    ['WHALE','WHALE','クジラ 🐳'],
    ['FOX','FOX','きつね 🦊'],
  ]},
  {id:'town', name:'学校・くらし・町', e:'🏫', words:[
    ['SCHOOL','SCHOOL','学校 🏫'],
    ['CLASSROOM','CLASSROOM','教室'],
    ['TEACHER','TEACHER','先生'],
    ['STUDENT','STUDENT','生徒・学生'],
    ['FRIEND','FRIEND','友だち'],
    ['PENCIL','PENCIL','えんぴつ ✏️'],
    ['ERASER','ERASER','消しゴム'],
    ['RULER','RULER','じょうぎ 📏'],
    ['NOTEBOOK','NOTEBOOK','ノート 📓'],
    ['BOOK','BOOK','本 📖'],
    ['BAG','BAG','かばん 👜'],
    ['DESK','DESK','つくえ'],
    ['CHAIR','CHAIR','いす 🪑'],
    ['CLOCK','CLOCK','かべや 台におく 時計 🕰️'],
    ['MATH','MATH','算数'],
    ['SCIENCE','SCIENCE','理科 🔬'],
    ['MUSIC','MUSIC','音楽 🎵'],
    ['ENGLISH','ENGLISH','英語'],
    ['JAPANESE','JAPANESE','国語・日本語'],
    ['HOMEWORK','HOMEWORK','しゅくだい'],
    ['LIBRARY','LIBRARY','図書館 📚'],
    ['GYM','GYM','体育館'],
    ['PARK','PARK','公園'],
    ['STATION','STATION','駅 🚉'],
    ['HOSPITAL','HOSPITAL','病院 🏥'],
    ['BANK','BANK','銀行 🏦'],
    ['ZOO','ZOO','動物園'],
    ['MUSEUM','MUSEUM','博物館・美術館'],
    ['RESTAURANT','RESTAURANT','レストラン 🍽️'],
    ['BAKERY','BAKERY','パン屋'],
    ['CASTLE','CASTLE','城 🏯'],
    ['TEMPLE','TEMPLE','寺'],
    ['SHRINE','SHRINE','神社 ⛩️'],
    ['BRIDGE','BRIDGE','橋 🌉'],
    ['RIVER','RIVER','川'],
    ['MOUNTAIN','MOUNTAIN','山 ⛰️'],
    ['BEACH','BEACH','海べ・すなはま 🏖️'],
    ['HOUSE','HOUSE','家 🏠'],
    ['FATHER','FATHER','父・お父さん'],
    ['MOTHER','MOTHER','母・お母さん'],
    ['FAMILY','FAMILY','家族 👪'],
    ['BUS','BUS','バス 🚌'],
    ['TRAIN','TRAIN','電車 🚃'],
    ['CAR','CAR','自動車 🚗'],
    ['BIKE','BIKE','自転車 🚲'],
  ]},
  {id:'move', name:'うごき・ようす', e:'🏃', words:[
    ['RUN','RUN','走る 🏃'],
    ['WALK','WALK','歩く 🚶'],
    ['SWIM','SWIM','泳ぐ 🏊'],
    ['JUMP','JUMP','ジャンプする・とびはねる'],
    ['EAT','EAT','食べる'],
    ['DRINK','DRINK','飲む'],
    ['SING','SING','歌う 🎤'],
    ['DANCE','DANCE','おどる 💃'],
    ['PLAY','PLAY','遊ぶ・（スポーツや楽器を）する'],
    ['STUDY','STUDY','勉強する'],
    ['READ','READ','読む'],
    ['WRITE','WRITE','書く ✍️'],
    ['SPEAK','SPEAK','話す'],
    ['LISTEN','LISTEN','（耳をすまして）聞く 👂'],
    ['SEE','SEE','見る・見える 👀'],
    ['COOK','COOK','料理する 🍳'],
    ['SLEEP','SLEEP','ねむる 😴'],
    ['GO','GO','行く'],
    ['COME','COME','来る'],
    ['BUY','BUY','買う 🛒'],
    ['HELP','HELP','手つだう・助ける'],
    ['LIKE','LIKE','好きだ'],
    ['WANT','WANT','ほしい'],
    ['OPEN','OPEN','開ける'],
    ['SIT','SIT','すわる'],
    ['STAND','STAND','立つ'],
    ['BIG','BIG','大きい'],
    ['SMALL','SMALL','小さい'],
    ['TALL','TALL','背が高い'],
    ['LONG','LONG','長い'],
    ['SHORT','SHORT','短い・背が低い'],
    ['HOT','HOT','暑い・熱い 🥵'],
    ['COLD','COLD','寒い・冷たい 🥶'],
    ['HAPPY','HAPPY','うれしい・しあわせな 😊'],
    ['SAD','SAD','悲しい 😢'],
    ['HUNGRY','HUNGRY','おなかが すいた'],
    ['FAST','FAST','速い'],
    ['NEW','NEW','新しい'],
    ['GOOD','GOOD','よい 👍'],
    ['BEAUTIFUL','BEAUTIFUL','美しい'],
    ['CUTE','CUTE','かわいい'],
    ['EASY','EASY','かんたんな'],
    ['DIFFICULT','DIFFICULT','むずかしい'],
    ['STRONG','STRONG','強い 💪'],
    ['FAMOUS','FAMOUS','有名な'],
  ]},
]});
