// 写真の データ（37_hajimete_oryori）。写真は photo/<p>.jpg（ウィキメディア・コモンズ、1000×750）。
// 名前あての 問題が あるので、番号は ばらばら。a/l/u＝とった人・ライセンス・もとの ページ。やさいの9まいは 35_yasai_okaimono の写し。
const PHOTOS=[
{"k": "shamoji", "p": "97", "n": "しゃもじ", "a": "Gribeco", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Shakushi.jpg"},
{"k": "otama", "p": "87", "n": "おたま", "a": "Moheen", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Ladle_(spoon)_-_%E0%A6%A1%E0%A6%BE%E0%A6%AC%E0%A7%81_-_DSC00527.jpg"},
{"k": "furaigaeshi", "p": "21", "n": "フライがえし", "a": "Evan-Amos", "l": "Public domain", "u": "https://commons.wikimedia.org/wiki/File:Kitchen-spatula.jpg"},
{"k": "furaipan", "p": "89", "n": "フライパン", "a": "User:Lcarsdata", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Frying_pan_with_black_handle.jpg"},
{"k": "nabe", "p": "91", "n": "なべ", "a": "RuinDig/Yuki Uchida", "l": "CC BY 4.0", "u": "https://commons.wikimedia.org/wiki/File:WMF-Fusiontec-Mineral-Multipot_05.jpg"},
{"k": "hocho", "p": "75", "n": "ほうちょう", "a": "Benlisquare", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:180mm_santoku_(top-down_view).jpg"},
{"k": "manaita", "p": "14", "n": "まないた", "a": "Fructibus", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Wooden_cutting_board_2017.jpg"},
{"k": "piiraa", "p": "90", "n": "ピーラー", "a": "Fred Klein", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Couteau-econome.jpg"},
{"k": "saibashi", "p": "57", "n": "さいばし", "a": "me (user:Potesara)", "l": "CC BY-SA 2.5", "u": "https://commons.wikimedia.org/wiki/File:Saibashi_with_normal_hashi.jpg"},
{"k": "zaru", "p": "66", "n": "ざる", "a": "Hustvedt", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Plastic_Colander.jpg"},
{"k": "keiryo_cup", "p": "77", "n": "けいりょうカップ", "a": "Rhetos", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Ein_Mikroliter_(Messbecher).jpg"},
{"k": "keiryo_spoon", "p": "23", "n": "けいりょうスプーン", "a": "Susan Slater", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:61_-_IMG_20150816_112616.jpg"},
{"k": "awadateki", "p": "68", "n": "あわだてき", "a": "Matti Blume", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Whisk_(IMG_0265).jpg"},
{"k": "suihanki", "p": "46", "n": "すいはんき", "a": "Julie Magro", "l": "CC BY 2.0", "u": "https://commons.wikimedia.org/wiki/File:Sanyo_Rice_Cooker_(4643347985).jpg"},
{"k": "kankisen", "p": "58", "n": "かんきせん", "a": "Steven Pavlov", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:General_Electric_Oven_Exhaust_Hood_Model_N320_003AD,_IMG02.jpg"},
{"k": "gasu", "p": "64", "n": "ガスコンロ", "a": "Palagiri", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Kitchen-_cooking_gas_stove.JPG"},
{"k": "ih", "p": "95", "n": "IHクッキングヒーター", "a": "Pic p ter", "l": "CC BY 3.0", "u": "https://commons.wikimedia.org/wiki/File:Induktionskochplatte.jpg"},
{"k": "sponji", "p": "28", "n": "スポンジ", "a": "Jiří Sedláček", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Small_yellow_green_sponge.jpg"},
{"k": "mizukiri", "p": "16", "n": "水きりかご", "a": "Mcapdevila", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Dish_rack.JPG"},
{"k": "tamago", "p": "96", "n": "たまご", "a": "Evan-Amos", "l": "Public domain", "u": "https://commons.wikimedia.org/wiki/File:White-%26-Brown-Eggs.jpg"},
{"k": "butaniku", "p": "62", "n": "ぶたにく", "a": "WCPCLM 2002258", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:SZ_%E6%B7%B1%E5%9C%B3_Shenzhen_%E7%A6%8F%E7%94%B0_Futian_%E7%9A%87%E5%BA%AD%E5%BB%A3%E5%A0%B4_Wongtee_Plaza_shop_%E6%BC%A2%E9%99%BD%E5%BB%B7%E8%87%AA%E5%8A%A9%E7%83%A4%E8%82%89_Hayaco_Barbecue_Restaurant_raw_beef_n_pork_slices_September_2025_N13P_01.jpg"},
{"k": "tofu", "p": "19", "n": "とうふ", "a": "yearofeats", "l": "CC BY 2.0", "u": "https://commons.wikimedia.org/wiki/File:Korean_food-Dubu-01.jpg"},
{"k": "wakame", "p": "85", "n": "わかめ", "a": "Fumikas Sagisavas", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Salted_wakame_leaves.jpg"},
{"k": "miso", "p": "56", "n": "みそ", "a": "https://publicdomainq.net/miso-0018849/", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Miso_001.jpg"},
{"k": "niboshi", "p": "65", "n": "にぼし", "a": "挪威 企鵝", "l": "CC BY-SA 2.0", "u": "https://commons.wikimedia.org/wiki/File:Niboshi,_Kawana_Dried_Foods,_Tsukiji,_Tokyo_-_Oct_17,_2005_(cropped).jpg"},
{"k": "curry_rice", "p": "93", "n": "カレーライス", "a": "Ocdp", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Beef_curry_rice_003.jpg"},
{"k": "yudetamago", "p": "50", "n": "ゆでたまご", "a": "Ramesh NG", "l": "CC BY-SA 2.0", "u": "https://commons.wikimedia.org/wiki/File:Boiled_Egg_-_Crossection.jpg"},
{"k": "medamayaki", "p": "55", "n": "めだまやき", "a": "Horacio Cambeiro", "l": "CC BY 3.0", "u": "https://commons.wikimedia.org/wiki/File:Pan-fried_egg.jpg"},
{"k": "misoshiru", "p": "76", "n": "みそしる", "a": "Ocdp", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Miso_Soup_001.jpg"},
{"k": "gohan", "p": "12", "n": "ごはん", "a": "Douglas Perkins", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:A_bowl_of_rice.jpg"},
{"k": "yasaiitame", "p": "61", "n": "やさいいため", "a": "CNEcija12345", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Stir_fried_mixed_vegetables.jpg"},
{"k": "salad", "p": "43", "n": "サラダ", "a": "Acabashi", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Side_salad_at_Sainsbury%27s_Low_Hall,_Chingford,_London_1_top_view.jpg"},
{"k": "jagaimo", "p": "69", "n": "じゃがいも", "a": "Midori", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Dieng_Potatoes.jpg"},
{"k": "ninjin", "p": "33", "n": "にんじん", "a": "domdomegg", "l": "CC BY 4.0", "u": "https://commons.wikimedia.org/wiki/File:Carrots_at_Ljubljana_Central_Market.JPG"},
{"k": "tamanegi", "p": "80", "n": "たまねぎ", "a": "Alex Lomas", "l": "CC BY 2.0", "u": "https://commons.wikimedia.org/wiki/File:Allium_cepa_(2944502550).jpg"},
{"k": "kyabetsu", "p": "39", "n": "キャベツ", "a": "Deborah Tjituka", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Cabbage_heads.jpg"},
{"k": "piman", "p": "83", "n": "ピーマン", "a": "Mike Mozart from Funny YouTube, USA", "l": "CC BY 2.0", "u": "https://commons.wikimedia.org/wiki/File:Green_Bell_Peppers_(22226099930).jpg"},
{"k": "kyuri", "p": "92", "n": "きゅうり", "a": "Eric Polk", "l": "CC BY-SA 4.0", "u": "https://commons.wikimedia.org/wiki/File:Japanese_cucumbers.jpg"},
{"k": "tomato", "p": "71", "n": "トマト", "a": "Softeis", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:Tomato_je.jpg"},
{"k": "retasu", "p": "53", "n": "レタス", "a": "Jeffery Martin", "l": "CC0", "u": "https://commons.wikimedia.org/wiki/File:Lettuce_in_a_stack.jpg"},
{"k": "negi", "p": "11", "n": "ねぎ", "a": "Genmewcaugsa", "l": "CC BY-SA 3.0", "u": "https://commons.wikimedia.org/wiki/File:HK_SYP_Best_of_Best_Vegetable_Peking_Welsh_onion_Allium_Aug-2012.JPG"}
];
